doctrine_migrations:
    migrations_paths:
        'Commerce\Migrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
    storage:
        table_storage:
            table_name: mc_migration_versions
