<?php

declare(strict_types=1);

namespace Commerce\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Marks prices generated by exchange-rate conversion so they can be refreshed or removed
 * without touching merchant-entered prices (source='manual').
 */
final class Version20260927190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Price source flag and sync state for automatic currency conversion.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE mc_price_fx_state (
            store_id BIGINT UNSIGNED NOT NULL,
            currency CHAR(3) NOT NULL,
            rate_used DECIMAL(30,12) NOT NULL,
            synced_at DATETIME(6) NOT NULL,
            PRIMARY KEY (store_id, currency),
            CONSTRAINT fk_price_fx_state_store FOREIGN KEY (store_id) REFERENCES mc_store(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $this->addSql("ALTER TABLE mc_price ADD source VARCHAR(16) NOT NULL DEFAULT 'manual' AFTER priority, ADD KEY idx_price_source_currency (store_id, source, currency, updated_at)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM mc_price WHERE source='fx'");
        $this->addSql('DROP TABLE mc_price_fx_state');
        $this->addSql('ALTER TABLE mc_price DROP KEY idx_price_source_currency, DROP COLUMN source');
    }
}
