<?php

declare(strict_types=1);

namespace Commerce\Core\I18n;

use Symfony\Component\HttpFoundation\RequestStack;
use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;

final class StorefrontUiTwigExtension extends AbstractExtension
{
    /** @var array<string,string>|null Lucide icon bodies generated by tools/build-lucide-icons.mjs */
    private static ?array $icons = null;

    public function __construct(
        private readonly StorefrontUiTranslator $translator,
        private readonly RequestStack $requests,
    ) {
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('ui_text', $this->text(...), ['needs_context' => true]),
            new TwigFunction('ui_catalog', $this->catalog(...), ['needs_context' => true]),
            new TwigFunction('ui_catalog_json', $this->catalogJson(...), ['needs_context' => true, 'is_safe' => ['html']]),
            new TwigFunction('ui_icon', $this->icon(...), ['is_safe' => ['html']]),
        ];
    }

    public function getFilters(): array
    {
        return [
            new TwigFilter('forum_ugc', $this->forumUgc(...), ['is_safe' => ['html']]),
            new TwigFilter('status_label', $this->statusLabel(...), ['needs_context' => true]),
        ];
    }

    public function icon(string $name, int $size = 20, string $class = ''): string
    {
        self::$icons ??= self::loadIcons();
        $body = self::$icons[$name] ?? '';
        if ($body === '') {
            return '';
        }
        // Sizes snap to the design-token scale (xs 14, sm 16, md 20, lg 24, xl 32).
        $size = match (true) {
            $size <= 14 => 14,
            $size <= 16 => 16,
            $size <= 20 => 20,
            $size <= 24 => 24,
            default => 32,
        };
        $safeClass = preg_replace('/[^a-zA-Z0-9_:\- ]/', '', $class) ?: '';
        $classAttr = trim('ui-icon ' . $safeClass);
        $fill = str_ends_with($name, '-filled') ? 'currentColor' : 'none';

        return sprintf(
            '<svg class="%s" width="%d" height="%d" viewBox="0 0 24 24" fill="%s" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">%s</svg>',
            htmlspecialchars($classAttr, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'),
            $size,
            $size,
            $fill,
            $body,
        );
    }

    /** @return array<string,string> */
    private static function loadIcons(): array
    {
        $file = dirname(__DIR__, 3) . '/resources/icons/lucide.json';
        $data = is_file($file) ? json_decode((string) file_get_contents($file), true) : null;

        return is_array($data['icons'] ?? null) ? $data['icons'] : [];
    }

    /** @param array<string,mixed> $context @param list<string> $prefixes */
    public function catalogJson(array $context, array $prefixes = []): string
    {
        $catalog = $this->catalog($context);
        if ($prefixes !== []) {
            $catalog = array_filter(
                $catalog,
                static function (string $key) use ($prefixes): bool {
                    foreach ($prefixes as $prefix) {
                        if (str_starts_with($key, (string) $prefix)) {
                            return true;
                        }
                    }
                    return false;
                },
                ARRAY_FILTER_USE_KEY,
            );
        }

        try {
            return json_encode($catalog, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
        } catch (\JsonException) {
            return '{}';
        }
    }

    public function forumUgc(string $text): string
    {
        $parts = preg_split('~(https?://[^\s<>]+)~iu', $text, -1, PREG_SPLIT_DELIM_CAPTURE);
        if (!is_array($parts)) {
            return nl2br(htmlspecialchars($text, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'));
        }

        $html = '';
        foreach ($parts as $part) {
            if (preg_match('~^https?://~iu', $part) === 1 && filter_var($part, FILTER_VALIDATE_URL) !== false) {
                $safe = htmlspecialchars($part, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
                $html .= '<a href="' . $safe . '" rel="ugc nofollow noopener noreferrer" target="_blank">' . $safe . '</a>';
                continue;
            }
            $html .= htmlspecialchars($part, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        }

        return nl2br($html, false);
    }

    /** @param array<string,mixed> $context @return array<string,string> */
    public function catalog(array $context): array
    {
        $locale = is_string($context['locale'] ?? null) ? trim($context['locale']) : ''; // a template loop variable named `locale` must not shadow the UI locale
        if ($locale === '') {
            $locale = $this->requests->getCurrentRequest()?->getLocale() ?? 'uk-UA';
        }

        return $this->translator->catalogFor($locale);
    }

    /** @param array<string,mixed> $context */
    /** Human label for an order/payment/fulfilment status code; unknown codes fall back to a readable form of the code. @param array<string,mixed> $context */
    public function statusLabel(array $context, mixed $code): string
    {
        $code = trim((string) $code);
        if ($code === '') {
            return '—';
        }
        $key = 'status.' . $code;
        $label = $this->text($context, $key);

        return $label !== $key ? $label : ucfirst(str_replace('_', ' ', $code));
    }

    public function text(array $context, string $key, array $replace = []): string
    {
        $locale = is_string($context['locale'] ?? null) ? trim($context['locale']) : ''; // a template loop variable named `locale` must not shadow the UI locale
        if ($locale === '') {
            $locale = $this->requests->getCurrentRequest()?->getLocale() ?? 'uk-UA';
        }

        return $this->translator->translate($key, $locale, $replace);
    }
}
